[package]
name = "metaculustetra"
version = "0.1.0"
authors = ["holomanga <holomanga@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11.6", features = ["blocking"]}
serde_json = "1.0.68"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.14"
env_logger = "0.9.0"